products:
  - name: バビロンの大富豪 「繁栄と富と幸福」はいかにして築かれるのか
    urls:
      - site: Amazon
        url: https://www.amazon.co.jp/dp/4901423126
      - site: 楽天ブックス
        url: https://books.rakuten.co.jp/rb/5817140/
